test:
  build: .
  command: py.test --pep8 --flakes

deploy-test:
  build: .
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
  command: apex deploy --alias test

deploy-prod:
  build: .
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
  command: apex deploy --alias prod

deploy-dry-run:
  build: .
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
  command: apex deploy --dry-run
