test:
  build: .
  command: py.test --pep8 --flakes

deploy-base: &deploy-base
  build: .
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION

deploy-test:
  <<: *deploy-base
  command: apex deploy --alias test

deploy-prod:
  <<: *deploy-base
  command: apex deploy --alias prod

deploy-dry-run:
  <<: *deploy-base
  command: apex deploy --dry-run
